-- AlterTable
ALTER TABLE `vendor` ADD COLUMN `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `paymentMethod` VARCHAR(191) NULL,
    ADD COLUMN `paymentStatus` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `region` VARCHAR(191) NULL;
