import swaggerJSDoc from "swagger-jsdoc";

const options = {
  definition: {
    openapi: "3.0.0",
    info: {
      title: "Paint App API Documentation",
      version: "1.0.0",
      description:
        "API documentation for the Paint Application backend. Includes authentication, products (paints), categories, users, vendors, and more.",
      contact: {
        name: "Developer",
      },
    },
    servers: [
      {
        url: "http://localhost:5000",
        description: "Local Development Server",
      },
      {
         url: "https://tovo-b.developteam.site/kids-tovo/api", 
         description: "Production/Live Server"
      }
    ],
    tags: [
      { name: "Auth", description: "تسجيل الدخول والتسجيل" },
      { name: "Users", description: "المستخدمون، الحساب الحالي، صورة البروفايل" },
      { name: "Designers", description: "المصممون وبروفايل المصمم" },
      {
        name: "Designs",
        description:
          "التصاميم (قائمة، تفاصيل)، طلب تنفيذ على تصميم، تعليقات، مفضلة، رابط مشاركة",
      },
      { name: "Painters", description: "فنيو الدهان، البروفايل، معرض أعمال التنفيذ" },
      { name: "VisitRequests", description: "طلبات زيارة الفني (موعد، عنوان، منطقة)" },
      { name: "Cart", description: "سلة المشتريات وإتمام الطلب" },
      {
        name: "Payments",
        description: "طرق الدفع المعروضة للتطبيق وتسجيل الطريقة عند الطلب (بدون بوابة دفع)",
      },
      {
        name: "Orders",
        description: "طلبات المستخدم الحالي وعرض فاتورة/تفاصيل كل طلب (يتطلب تسجيل الدخول)",
      },
      { name: "Vendor Requests", description: "طلبات الجملة، التحول إلى تاجر، والموافقة من لوحة الإدارة" },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          bearerFormat: "JWT",
        },
      },
      schemas: {
        ApiError: {
          type: "object",
          properties: {
            error: { type: "string", description: "Error message (Arabic or English)" },
          },
        },
        Category: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid", description: "Category id" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
          },
        },
        CategoryWithPaintCount: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            name: { type: "string" },
            description: { type: "string", nullable: true },
            _count: {
              type: "object",
              properties: {
                paints: { type: "integer", description: "Number of paints in this category" },
              },
            },
          },
        },
        CategoryCreateBody: {
          type: "object",
          description: "يفضل إرسال الاسم بالعربي والإنجليزي. يدعم nameAr/nameEn وأيضًا name_ar/name_en للتوافق.",
          properties: {
            name: { type: "string" },
            nameAr: { type: "string" },
            nameEn: { type: "string" },
            name_en: { type: "string" },
            name_ar: { type: "string" },
            description: { type: "string", nullable: true },
          },
          example: {
            nameAr: "دهانات داخلية",
            nameEn: "Interior Paints",
          },
        },
        CategoryUpdateBody: {
          type: "object",
          properties: {
            name: { type: "string" },
            nameAr: { type: "string" },
            nameEn: { type: "string" },
            name_en: { type: "string" },
            name_ar: { type: "string" },
            description: { type: "string", nullable: true },
          },
        },
        CategoryDeleted: {
          type: "object",
          properties: {
            message: { type: "string", example: "Category deleted" },
          },
        },
        PaintDetail: {
          type: "object",
          description: "Normalized paint object returned by GET /paint/{id}",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            price: { type: "number" },
            description: { type: "string", nullable: true },
            categoryId: { type: "number", description: "May be 0 if missing in DB" },
            vendorId: { type: "number" },
            base: { type: "string", enum: ["water", "oil", "wood"] },
            coatHours: { type: "number" },
            coverage: { type: "number" },
            dryDays: { type: "number" },
            finish: { type: "string", enum: ["matte", "semi_gloss", "gloss"] },
            unit: { type: "string", enum: ["liter", "kg"] },
            usage: { type: "string" },
            image: { type: "string", nullable: true },
            stock: { type: "number" },
            inStock: { type: "boolean" },
            isActive: { type: "boolean" },
            weightKg: { type: "number" },
            offerId: { type: "number", nullable: true },
            type: { type: "string" },
            sku: { type: "string", nullable: true },
            wholesalePrice: { type: "number", nullable: true },
            createdAt: { type: "string", format: "date-time", nullable: true },
            updatedAt: { type: "string", format: "date-time", nullable: true },
          },
        },
        PaintListItem: {
          type: "object",
          description: "Raw paint row from DB; may include minStockLevel on list endpoint",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            type: { type: "string" },
            price: { type: "number" },
            description: { type: "string", nullable: true },
            categoryId: { type: "string" },
            vendorId: { type: "string" },
            base: { type: "string", enum: ["water", "oil", "wood"] },
            coatHours: { type: "integer" },
            coverage: { type: "number" },
            dryDays: { type: "integer" },
            finish: { type: "string", enum: ["matte", "semi_gloss", "gloss"] },
            unit: { type: "string", enum: ["liter", "kg"] },
            usage: { type: "string", enum: ["indoor", "outdoor", "both"] },
            image: { type: "string", nullable: true },
            stock: { type: "integer" },
            inStock: { type: "boolean" },
            isActive: { type: "boolean" },
            weightKg: { type: "number", nullable: true },
            wholesalePrice: { type: "number", nullable: true },
            sku: { type: "string", nullable: true },
            offerId: { type: "string", nullable: true },
            minStockLevel: { type: "number", description: "Default 5 when absent in row" },
            createdAt: { type: "string", format: "date-time" },
            updatedAt: { type: "string", format: "date-time" },
          },
          additionalProperties: true,
        },
        PaintCreateBody: {
          type: "object",
          required: ["nameAr", "nameEn", "price"],
          properties: {
            name: { type: "string" },
            nameAr: { type: "string", description: "اسم المنتج بالعربي (مطلوب)" },
            nameEn: { type: "string", description: "اسم المنتج بالإنجليزي (مطلوب)" },
            type: { type: "string", default: "paint" },
            description: { type: "string", nullable: true },
            descriptionAr: { type: "string", nullable: true },
            descriptionEn: { type: "string", nullable: true },
            price: { type: "number" },
            unit: { type: "string", enum: ["liter", "kg"], default: "kg" },
            coverage: { type: "number" },
            coatHours: { type: "number" },
            dryDays: { type: "integer", minimum: 0 },
            finish: { type: "string", enum: ["matte", "semi_gloss", "gloss"] },
            usage: { type: "string", enum: ["indoor", "outdoor", "both"] },
            base: { type: "string", enum: ["water", "oil", "wood"] },
            stock: { type: "integer", minimum: 0 },
            categoryId: { type: "string", description: "UUID of category" },
            vendorId: {
              type: "string",
              nullable: true,
              description: "اختياري؛ مخزون الإدارة يُترك فارغًا أو null",
            },
            image: { type: "string", nullable: true },
            offerId: { type: "number", nullable: true },
            weightKg: { type: "number", minimum: 0, default: 1 },
            wholesalePrice: { type: "number", minimum: 0, nullable: true },
            sku: { type: "string", nullable: true },
          },
        },
        PaintUpdateBody: {
          type: "object",
          description: "Partial update; at least one field required",
          properties: {
            name: { type: "string" },
            nameAr: { type: "string" },
            nameEn: { type: "string" },
            price: { type: "number" },
            description: { type: "string", nullable: true },
            descriptionAr: { type: "string", nullable: true },
            descriptionEn: { type: "string", nullable: true },
            categoryId: { type: "string" },
            vendorId: { type: "string", nullable: true, description: "ارسال null لإزالة الربط بالمورد" },
            base: { type: "string", enum: ["water", "oil", "wood"] },
            coatHours: { type: "number" },
            coverage: { type: "number" },
            dryDays: { type: "integer" },
            finish: { type: "string", enum: ["matte", "semi_gloss", "gloss"] },
            unit: { type: "string", enum: ["liter", "kg"] },
            usage: { type: "string", enum: ["indoor", "outdoor", "both"] },
            image: { type: "string", nullable: true },
            stock: { type: "integer" },
            isActive: { type: "boolean" },
            offerId: { type: "number", nullable: true },
            type: { type: "string" },
            weightKg: { type: "number" },
            wholesalePrice: { type: "number", nullable: true },
            sku: { type: "string", nullable: true },
          },
        },
        PaintCreateResponse: {
          type: "object",
          properties: {
            message: { type: "string", example: "Paint created" },
            paint: { type: "object", additionalProperties: true, description: "Last inserted row" },
          },
        },
        PaintUpdateResponse: {
          type: "object",
          properties: {
            message: { type: "string", example: "Paint updated" },
            paint: { type: "object", additionalProperties: true },
          },
        },
        PaintDeleted: {
          type: "object",
          properties: {
            message: { type: "string", example: "Paint deleted" },
          },
        },
        Design: {
          type: "object",
          properties: {
            id: { type: "string" },
            designerId: { type: "string" },
            designerName: { type: "string", nullable: true },
            title: { type: "string" },
            description: { type: "string" },
            imageUrl: { type: "string" },
            videoUrl: { type: "string", nullable: true },
            createdAt: { type: "string", format: "date-time", nullable: true },
            updatedAt: { type: "string", format: "date-time", nullable: true },
          },
        },
        DesignCreateBody: {
          type: "object",
          required: ["title", "description", "imageUrl"],
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            imageUrl: { type: "string" },
            videoUrl: { type: "string", nullable: true },
            designerId: { type: "string", description: "Admin can set owner designerId" },
          },
        },
        DesignUpdateBody: {
          type: "object",
          properties: {
            title: { type: "string" },
            description: { type: "string" },
            imageUrl: { type: "string" },
            videoUrl: { type: "string", nullable: true },
          },
        },
        DesignCommentBody: {
          type: "object",
          required: ["text"],
          properties: {
            text: { type: "string" },
          },
        },
        DesignRequestBody: {
          type: "object",
          required: ["description"],
          description: "طلب عميل لتنفيذ أو تعديل مرتبط بتصميم معيّن (يُرسل مع POST /designs/{id}/requests).",
          properties: {
            description: {
              type: "string",
              minLength: 1,
              description: "وصف الطلب (إلزامي) — مثال: تفاصيل الألوان، المقاسات، الميزانية",
            },
            imageUrl: {
              type: "string",
              nullable: true,
              description: "رابط صورة مرجعية اختياري",
            },
            videoUrl: {
              type: "string",
              nullable: true,
              description: "رابط فيديو مرجعي اختياري",
            },
          },
          example: {
            description: "أرغب بتنفيذ نفس التصميم لغرفة معيشة 4×5 م مع لون جدران أوف وايت.",
            imageUrl: "https://example.com/ref.jpg",
            videoUrl: null,
          },
        },
        DesignRequestStatusBody: {
          type: "object",
          required: ["status"],
          description: "تحديث حالة طلب التصميم (المصمم صاحب التصميم أو الأدمن) عبر PUT /designs/{designId}/requests/{requestId}/status.",
          properties: {
            status: {
              type: "string",
              enum: ["pending", "accepted", "rejected", "completed"],
              description: "الحالة الجديدة للطلب",
            },
          },
          example: { status: "accepted" },
        },
        DesignRequest: {
          type: "object",
          description:
            "طلب عميل على تصميم. حقلا clientName و clientPhone يُعادان في استجابة GET /designs/{id}/requests لصاحب التصميم أو الأدمن فقط.",
          properties: {
            id: { type: "string", format: "uuid" },
            designId: { type: "string", description: "معرف التصميم" },
            clientUserId: { type: "string", description: "معرف المستخدم الذي قدم الطلب" },
            clientName: {
              type: "string",
              nullable: true,
              description: "اسم العميل (مُضاف في GET عند جلب الطلبات لصاحب التصميم/الأدمن)",
            },
            clientPhone: {
              type: "string",
              nullable: true,
              description: "جوال العميل (مُضاف في GET عند جلب الطلبات لصاحب التصميم/الأدمن)",
            },
            description: { type: "string" },
            imageUrl: { type: "string", nullable: true },
            videoUrl: { type: "string", nullable: true },
            status: {
              type: "string",
              enum: ["pending", "accepted", "rejected", "completed"],
              description: "حالة الطلب؛ الافتراضي عند الإنشاء pending. المصمم يحدّثها عبر PUT .../status.",
            },
            createdAt: { type: "string", format: "date-time" },
          },
        },
        FavoriteToggleResponse: {
          type: "object",
          properties: {
            favorited: { type: "boolean" },
          },
        },
        DesignShareResponse: {
          type: "object",
          properties: {
            designId: { type: "string" },
            shareUrl: { type: "string" },
          },
        },
        WholesaleRequestBody: {
          type: "object",
          description:
            "طلب تفعيل أسعار الجملة (بدون تغيير الدور إلى تاجر). جميع الحقول التالية إلزامية ما عدا city.",
          required: [
            "userId",
            "shopName",
            "taxRegistration",
            "companyType",
            "fullName",
            "email",
            "phone",
            "companyAddress",
          ],
          properties: {
            userId: { type: "string", description: "معرف المستخدم الحالي" },
            shopName: { type: "string", description: "اسم الشركة / المحل" },
            taxRegistration: { type: "string", description: "الرقم الضريبي" },
            companyType: { type: "string", description: "نوع الشركة (يُخزَّن أيضاً ضمن region كـ type:...)" },
            fullName: { type: "string", description: "الاسم الكامل لصاحب الطلب" },
            email: { type: "string", format: "email" },
            phone: { type: "string", description: "رقم الجوال" },
            companyAddress: { type: "string", description: "عنوان الشركة" },
            city: { type: "string", nullable: true, description: "اختياري؛ الافتراضي N/A" },
          },
        },
        VendorUpgradeRequestBody: {
          type: "object",
          description:
            "طلب التحول إلى حساب تاجر. جميع الحقول التالية إلزامية ما عدا city.",
          required: [
            "userId",
            "shopName",
            "taxRegistration",
            "companyType",
            "fullName",
            "email",
            "phone",
            "companyAddress",
          ],
          properties: {
            userId: { type: "string", description: "معرف المستخدم الحالي" },
            shopName: { type: "string", description: "اسم الشركة / المحل" },
            taxRegistration: { type: "string", description: "الرقم الضريبي" },
            companyType: { type: "string", description: "نوع الشركة" },
            fullName: { type: "string", description: "الاسم الكامل لصاحب الطلب" },
            email: { type: "string", format: "email" },
            phone: { type: "string", description: "رقم الجوال" },
            companyAddress: { type: "string", description: "عنوان الشركة" },
            city: { type: "string", nullable: true, description: "اختياري؛ الافتراضي N/A" },
          },
        },
        VendorRequestSubmitResponse: {
          type: "object",
          description: "استجابة إنشاء أو تحديث طلب (قد لا يتضمن request عند رسالة فقط)",
          properties: {
            message: { type: "string" },
            request: {
              type: "object",
              description: "سجل vendor بعد الإنشاء أو التحديث",
            },
          },
        },
        ApproveVendorBody: {
          type: "object",
          properties: {
            isApproved: { type: "boolean", description: "عند true ونوع الطلب VENDOR يُرقّى المستخدم إلى vendor" },
            paymentStatus: { type: "boolean" },
          },
        },
        PendingVendorRequest: {
          type: "object",
          properties: {
            id: { type: "string" },
            userId: { type: "string" },
            shopName: { type: "string" },
            city: { type: "string" },
            address: { type: "string", nullable: true },
            region: {
              type: "string",
              nullable: true,
              description: "يُخزَّن نوع الشركة بصيغة type:{companyType}",
            },
            taxRegistration: { type: "string", nullable: true },
            paymentStatus: { type: "boolean" },
            isApproved: { type: "boolean" },
            requestType: {
              type: "string",
              enum: ["VENDOR", "WHOLESALE"],
              description: "نوع الطلب: تحويل تاجر أو شراء بالجملة فقط",
            },
            user: {
              type: "object",
              nullable: true,
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                email: { type: "string" },
                phone: { type: "string" },
              },
            },
          },
        },
        Paint: {
          type: "object",
          description: "Legacy aggregate schema; prefer PaintDetail / PaintListItem",
          required: ["name", "price"],
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            type: { type: "string", default: "paint" },
            description: { type: "string", nullable: true },
            price: { type: "number" },
            unit: { type: "string", enum: ["liter", "kg"] },
            coverage: { type: "number" },
            coatHours: { type: "number" },
            dryDays: { type: "integer" },
            finish: { type: "string", enum: ["matte", "semi_gloss", "gloss"] },
            usage: { type: "string", enum: ["indoor", "outdoor", "both"] },
            base: { type: "string", enum: ["water", "oil", "wood"] },
            stock: { type: "integer" },
            categoryId: { type: "string" },
            vendorId: { type: "string" },
            image: { type: "string", nullable: true },
            weightKg: { type: "number" },
            offerId: { type: "string", nullable: true },
            wholesalePrice: { type: "number", nullable: true },
            sku: { type: "string", nullable: true },
          },
        },
        User: {
          type: "object",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            role: { type: "string", enum: ["user", "admin", "painter", "vendor", "designer"] },
            avatarUrl: { type: "string", nullable: true, description: "مسار نسبي مثل /uploads/..." },
            isActive: {
              type: "boolean",
              description: "الحساب مفعّل؛ الافتراضي true للمستخدمين الجدد",
            },
            status: {
              type: "boolean",
              description: "نفس معنى isActive (للوحة التحكم)",
            },
            createdAt: { type: "string", format: "date-time", nullable: true },
          },
        },
        MeProfileResponse: {
          type: "object",
          description: "المستخدم بدون كلمة المرور + canBuyWholesale + بروفايل مصمم/فني عند وجوده",
          properties: {
            id: { type: "string" },
            name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            role: { type: "string" },
            avatarUrl: { type: "string", nullable: true },
            isActive: { type: "boolean" },
            status: { type: "boolean", description: "نسخة لوحة التحكم من isActive" },
            createdAt: { type: "string", format: "date-time", nullable: true },
            canBuyWholesale: { type: "boolean" },
            designerProfile: {
              type: "object",
              nullable: true,
              description: "عند role=designer",
              properties: {
                id: { type: "string" },
                userId: { type: "string" },
                experience: { type: "integer", nullable: true },
                specialties: { type: "string", nullable: true },
                rating: { type: "number", nullable: true },
                portfolio: { type: "string", nullable: true },
                bio: { type: "string", nullable: true },
                location: { type: "string", nullable: true },
              },
            },
            painterProfile: {
              type: "object",
              nullable: true,
              description: "عند role=painter؛ يتضمن gallery",
              properties: {
                id: { type: "string" },
                userId: { type: "string" },
                city: { type: "string" },
                address: { type: "string", nullable: true },
                experience: { type: "integer" },
                serviceType: { type: "string" },
                bio: { type: "string", nullable: true },
                rating: { type: "number" },
                gallery: {
                  type: "array",
                  items: { $ref: "#/components/schemas/PainterGalleryItem" },
                },
              },
            },
          },
        },
        PainterGalleryItem: {
          type: "object",
          properties: {
            id: { type: "string" },
            painterId: { type: "string" },
            imageUrl: { type: "string", description: "مسار نسبي للصورة" },
          },
        },
        UserUpdateBody: {
          type: "object",
          properties: {
            name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            password: { type: "string" },
            role: { type: "string", description: "للمشرف فقط" },
            avatarUrl: { type: "string", nullable: true },
          },
        },
        AvatarUploadResponse: {
          type: "object",
          properties: {
            avatarUrl: { type: "string" },
            user: { $ref: "#/components/schemas/User" },
          },
        },
        DesignerProfileResponse: {
          type: "object",
          properties: {
            userId: { type: "string" },
            profileId: { type: "string", nullable: true },
            experience: { type: "integer", nullable: true },
            specialties: { type: "string", nullable: true },
            rating: { type: "number", nullable: true },
            portfolio: { type: "string", nullable: true },
            bio: { type: "string", nullable: true },
            location: { type: "string", nullable: true },
            user: { $ref: "#/components/schemas/User" },
          },
        },
        DesignerUpdateBody: {
          type: "object",
          properties: {
            name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            experience: { type: "integer", nullable: true },
            specialties: { type: "string", nullable: true },
            rating: { type: "number", nullable: true },
            portfolio: { type: "string", nullable: true },
            bio: { type: "string", nullable: true },
            location: { type: "string", nullable: true },
          },
        },
        PainterWithGallery: {
          type: "object",
          properties: {
            id: { type: "string" },
            userId: { type: "string" },
            city: { type: "string" },
            address: { type: "string", nullable: true },
            experience: { type: "integer" },
            serviceType: { type: "string" },
            bio: { type: "string", nullable: true },
            rating: { type: "number" },
            user: { $ref: "#/components/schemas/User" },
            gallery: {
              type: "array",
              items: { $ref: "#/components/schemas/PainterGalleryItem" },
            },
          },
        },
        PainterMeUpdateBody: {
          type: "object",
          properties: {
            name: { type: "string" },
            email: { type: "string" },
            phone: { type: "string" },
            city: { type: "string" },
            address: { type: "string", nullable: true },
            experience: { type: "integer" },
            serviceType: { type: "string" },
            bio: { type: "string", nullable: true },
          },
        },
        PainterCreateBody: {
          type: "object",
          required: ["userId"],
          properties: {
            userId: { type: "string" },
            city: { type: "string" },
            address: { type: "string", nullable: true },
            experience: { type: "integer" },
            serviceType: { type: "string" },
          },
          example: {
            userId: "a3ba5f2b-83df-4f2f-b42f-b182a496d6b3",
            city: "Riyadh",
            address: "Al Olaya",
            experience: 4,
            serviceType: "interior",
          },
        },
        PainterUpdateBody: {
          type: "object",
          properties: {
            city: { type: "string" },
            address: { type: "string", nullable: true },
            experience: { type: "integer" },
            serviceType: { type: "string" },
            bio: { type: "string", nullable: true },
          },
          example: {
            city: "Jeddah",
            address: "Al Rawdah",
            experience: 6,
            serviceType: "both",
            bio: "Painter specialized in indoor/outdoor projects.",
          },
        },
        CartItemInput: {
          type: "object",
          required: ["paintId", "quantity"],
          properties: {
            paintId: { type: "string" },
            quantity: { type: "integer", minimum: 1 },
          },
        },
        CartItemUpdateBody: {
          type: "object",
          required: ["quantity"],
          properties: {
            quantity: { type: "integer", minimum: 1 },
          },
        },
        CartItemResponse: {
          type: "object",
          properties: {
            id: { type: "string" },
            paintId: { type: "string" },
            quantity: { type: "integer" },
            unitPrice: { type: "number" },
            lineTotal: { type: "number" },
            paint: {
              type: "object",
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                image: { type: "string", nullable: true },
                price: { type: "number" },
                wholesalePrice: { type: "number", nullable: true },
                stock: { type: "integer" },
              },
            },
          },
        },
        CartResponse: {
          type: "object",
          properties: {
            userId: { type: "string" },
            canBuyWholesale: { type: "boolean" },
            items: {
              type: "array",
              items: { $ref: "#/components/schemas/CartItemResponse" },
            },
            subtotal: { type: "number" },
            discountValue: { type: "number", description: "قيمة خصم الكوبون على مستوى السلة" },
            total: { type: "number" },
            couponCode: { type: "string", nullable: true },
            couponValid: { type: "boolean", nullable: true },
          },
        },
        PaymentMethodId: {
          type: "string",
          enum: ["visa", "mastercard", "apple_pay"],
          description: "طريقة الدفع المحفوظة مع الطلب (تسجيل فقط)",
        },
        CheckoutRequestBody: {
          type: "object",
          required: ["paymentMethod"],
          description:
            "إتمام الطلب من السلة. paymentMethod إلزامي، وبيانات الشحن اختيارية لكن يفضل إرسالها لعرضها في تفاصيل الطلب. يدعم أيضاً الحقول البديلة: shippingCity, shippingPhone, address, zipCode.",
          properties: {
            paymentMethod: { $ref: "#/components/schemas/PaymentMethodId" },
            city: { type: "string", nullable: true },
            addressLine1: { type: "string", nullable: true },
            addressLine2: { type: "string", nullable: true },
            postalCode: { type: "string", nullable: true },
            phone: { type: "string", nullable: true },
            shippingCity: { type: "string", nullable: true, description: "Alias for city" },
            shippingPhone: { type: "string", nullable: true, description: "Alias for phone" },
            address: { type: "string", nullable: true, description: "Alias for addressLine1" },
            zipCode: { type: "string", nullable: true, description: "Alias for postalCode" },
            couponCode: { type: "string", nullable: true, description: "كود الكوبون (اختياري)" },
          },
          example: {
            paymentMethod: "visa",
            city: "Riyadh",
            addressLine1: "King Fahd Rd, Building 15",
            addressLine2: "Floor 2, Apt 6",
            postalCode: "12271",
            phone: "+9665XXXXXXX",
          },
        },
        ShippingInfo: {
          type: "object",
          properties: {
            city: { type: "string", nullable: true },
            addressLine1: { type: "string", nullable: true },
            addressLine2: { type: "string", nullable: true },
            postalCode: { type: "string", nullable: true },
            phone: { type: "string", nullable: true },
          },
        },
        PaymentMethodOption: {
          type: "object",
          properties: {
            id: { $ref: "#/components/schemas/PaymentMethodId" },
            label: { type: "string", example: "Visa" },
          },
        },
        CheckoutResponse: {
          type: "object",
          properties: {
            message: { type: "string" },
            orderId: { type: "string" },
            invoiceNumber: { type: "string" },
            subtotalPrice: { type: "number" },
            discountValue: { type: "number" },
            couponCode: { type: "string", nullable: true },
            totalPrice: { type: "number" },
            paymentMethod: { $ref: "#/components/schemas/PaymentMethodId" },
            shipping: {
              allOf: [{ $ref: "#/components/schemas/ShippingInfo" }],
              nullable: true,
            },
            items: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  paintId: { type: "string" },
                  paintName: { type: "string" },
                  quantity: { type: "integer" },
                  unitPrice: { type: "number" },
                  lineTotal: { type: "number" },
                },
              },
            },
          },
        },
        MyOrderLineItem: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            paintId: { type: "string" },
            quantity: { type: "integer" },
            unitPrice: { type: "number", nullable: true },
            lineTotal: { type: "number" },
            paint: {
              type: "object",
              nullable: true,
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                image: { type: "string", nullable: true },
                price: { type: "number" },
              },
            },
          },
        },
        MyOrderListItem: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            orderNumber: { type: "string", example: "ORD-uuid…" },
            invoiceNumber: { type: "string", example: "INV-uuid…" },
            totalPrice: { type: "number" },
            status: { type: "string", description: "حالة الطلب في النظام (مثل pending، delivered)" },
            invoiceStatus: {
              type: "string",
              enum: ["paid", "pending"],
              description: "مدفوع إذا اكتمل التسليم",
            },
            createdAt: { type: "string", format: "date-time" },
            paymentMethod: {
              allOf: [{ $ref: "#/components/schemas/PaymentMethodId" }],
              nullable: true,
              description: "قد يكون null لطلبات قديمة",
            },
            shipping: {
              allOf: [{ $ref: "#/components/schemas/ShippingInfo" }],
              nullable: true,
            },
            items: {
              type: "array",
              items: { $ref: "#/components/schemas/MyOrderLineItem" },
            },
          },
        },
        MyOrderDetail: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            userId: { type: "string" },
            painterId: { type: "string", nullable: true },
            totalPrice: { type: "number" },
            status: { type: "string" },
            createdAt: { type: "string", format: "date-time" },
            area: { type: "number", nullable: true },
            serviceDate: { type: "string", format: "date-time", nullable: true },
            serviceTime: { type: "string", nullable: true },
            zone: { type: "string", nullable: true },
            orderNumber: { type: "string" },
            invoiceNumber: { type: "string" },
            invoiceStatus: { type: "string", enum: ["paid", "pending"] },
            paymentMethod: {
              allOf: [{ $ref: "#/components/schemas/PaymentMethodId" }],
              nullable: true,
            },
            shipping: {
              allOf: [{ $ref: "#/components/schemas/ShippingInfo" }],
              nullable: true,
            },
            items: {
              type: "array",
              items: { $ref: "#/components/schemas/MyOrderLineItem" },
            },
          },
        },
        DashboardInvoiceRow: {
          type: "object",
          description: "صف يُعاد من GET /api/invoices",
          properties: {
            id: { type: "string", format: "uuid" },
            invoiceNumber: { type: "string" },
            amount: { type: "number" },
            status: { type: "string", enum: ["paid", "pending"] },
            createdAt: { type: "string", format: "date-time" },
            customer: {
              type: "object",
              nullable: true,
              properties: {
                id: { type: "string" },
                name: { type: "string" },
                email: { type: "string" },
                phone: { type: "string", nullable: true },
              },
            },
            order: {
              type: "object",
              description: "كائن الطلب الأصلي مع source",
            },
          },
        },
        MessageOk: {
          type: "object",
          properties: {
            message: { type: "string", example: "Deleted" },
          },
        },
        LoginResponse: {
          type: "object",
          properties: {
            message: { type: "string" },
            token: {
              type: "string",
              description:
                "JWT يحتوي على id و role و canBuyWholesale (تاجر معتمد، أو دور vendor/designer، أو موافقة جملة)",
            },
            user: { $ref: "#/components/schemas/User" },
          },
        },
        VisitRequest: {
          type: "object",
          properties: {
            id: { type: "string", format: "uuid" },
            clientUserId: { type: "string" },
            clientName: { type: "string", nullable: true, description: "اسم العميل (مفيد للفني/الأدمن)" },
            clientPhone: { type: "string", nullable: true, description: "رقم جوال العميل (مفيد للفني/الأدمن)" },
            painterId: { type: "string" },
            scheduledDate: { type: "string", description: "YYYY-MM-DD" },
            scheduledTime: { type: "string" },
            area: { type: "number", nullable: true },
            region: { type: "string", nullable: true },
            address: { type: "string" },
            status: { type: "string", enum: ["pending", "accepted", "rejected", "completed"] },
            createdAt: { type: "string", format: "date-time" },
            notes: { type: "string", nullable: true },
          },
        },
        VisitRequestCreateBody: {
          type: "object",
          required: ["painterId", "scheduledDate", "scheduledTime", "address"],
          description:
            "ينطبق على POST /visit-requests وأيضًا POST /painter-requests (alias).",
          properties: {
            painterId: { type: "string" },
            scheduledDate: { type: "string", description: "YYYY-MM-DD" },
            scheduledTime: { type: "string" },
            area: { type: "number", nullable: true },
            region: { type: "string", nullable: true, description: "المنطقة / الحي" },
            address: { type: "string", description: "عنوان العميل الكامل لموعد الزيارة" },
            notes: { type: "string", nullable: true },
          },
          example: {
            painterId: "f1942d5f-1b4f-4f3f-8d8e-e3b0f1f3375a",
            scheduledDate: "2026-03-28",
            scheduledTime: "14:30",
            area: 120,
            region: "Al Yasmin",
            address: "King Fahd Rd, Building 15, Floor 2",
            notes: "Please call before arriving.",
          },
        },
        PainterReviewCreateBody: {
          type: "object",
          required: ["painterId", "review", "rating"],
          properties: {
            painterId: { type: "string", format: "uuid" },
            review: { type: "string" },
            rating: { type: "number", minimum: 1, maximum: 5 },
          },
        },
      },
    },
    security: [
      {
        bearerAuth: [],
      },
    ],
  },
  apis: ["./src/server.js", "./src/routes/*.js", "./src/controllers/*.js"], // include paths to files containing documentation
};

export const swaggerSpec = swaggerJSDoc(options);
